# Generated by Django 3.0.8 on 2020-08-01 11:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policeStation', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=25)),
                ('place_of_occurence', models.TextField()),
                ('time_of_occurence', models.DateField()),
                ('time_when_registered', models.DateField()),
                ('nature_of_offence', models.TextField()),
                ('sections_under_crime_falls', models.TextField()),
                ('description_of_accused', models.TextField()),
                ('complaint', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'complainant'), (2, 'volunteer'), (3, 'sho'), (4, 'witness')])),
                ('name', models.CharField(max_length=50)),
                ('father', models.CharField(blank=True, max_length=50, null=True)),
                ('husband', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('aadhar_card', models.CharField(default='1234567890', max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(12)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='basic.User')),
            ],
        ),
        migrations.CreateModel(
            name='SHO',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='basic.User')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='basic.User')),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic.User')),
                ('witness_for_fir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.FIR')),
            ],
        ),
        migrations.AddField(
            model_name='fir',
            name='complainant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Complainant'),
        ),
    ]
