# Generated by Django 3.0.8 on 2020-08-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='witness',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
